version: "3.8"
services:
  redis:
    image: redis
    container_name: redis-cache
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
    command: npm run dev

volumes:
  redis_volume_data:
